include("setup.jl")

include("testsets/mesharray_basic.jl")
include("testsets/vertical_dim.jl")
include("testsets/regional_integration.jl")
include("testsets/transport.jl")
include("testsets/gcmfaces.jl")
include("testsets/unitgrid.jl")
include("testsets/nemo_grid.jl")
include("testsets/gridspec.jl")
include("testsets/plotting_makie.jl")
include("testsets/nanmath.jl")
include("testsets/plotting_basemap.jl")
include("testsets/polygon_ops.jl")
include("testsets/doctests.jl")
